# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Qgis2Doc
                                 A QGIS plugin
 Layerattribute in Wordvorlage einfügen
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-29
        copyright            : (C) 2020 by eGov/GIS
        email                : gis@stadt.erlangen.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Qgis2Doc class from file Qgis2Doc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgis_2_doc import Qgis2Doc
    return Qgis2Doc(iface)
